// Mocks generated by Mockito 5.4.6 from annotations
// in robot_flower_princess_front/test/unit/data/repositories/game_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:robot_flower_princess_front/data/datasources/game_remote_datasource.dart'
    as _i3;
import 'package:robot_flower_princess_front/data/models/game_model.dart' as _i2;
import 'package:robot_flower_princess_front/domain/value_objects/action_type.dart'
    as _i5;
import 'package:robot_flower_princess_front/domain/value_objects/direction.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameModel_0 extends _i1.SmartFake implements _i2.GameModel {
  _FakeGameModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRemoteDataSource extends _i1.Mock
    implements _i3.GameRemoteDataSource {
  MockGameRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GameModel> createGame(
    String? name,
    int? boardSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGame,
          [
            name,
            boardSize,
          ],
        ),
        returnValue: _i4.Future<_i2.GameModel>.value(_FakeGameModel_0(
          this,
          Invocation.method(
            #createGame,
            [
              name,
              boardSize,
            ],
          ),
        )),
      ) as _i4.Future<_i2.GameModel>);

  @override
  _i4.Future<List<_i2.GameModel>> getGames() => (super.noSuchMethod(
        Invocation.method(
          #getGames,
          [],
        ),
        returnValue: _i4.Future<List<_i2.GameModel>>.value(<_i2.GameModel>[]),
      ) as _i4.Future<List<_i2.GameModel>>);

  @override
  _i4.Future<_i2.GameModel> getGame(String? gameId) => (super.noSuchMethod(
        Invocation.method(
          #getGame,
          [gameId],
        ),
        returnValue: _i4.Future<_i2.GameModel>.value(_FakeGameModel_0(
          this,
          Invocation.method(
            #getGame,
            [gameId],
          ),
        )),
      ) as _i4.Future<_i2.GameModel>);

  @override
  _i4.Future<_i2.GameModel> executeAction(
    String? gameId,
    _i5.ActionType? action,
    _i6.Direction? direction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeAction,
          [
            gameId,
            action,
            direction,
          ],
        ),
        returnValue: _i4.Future<_i2.GameModel>.value(_FakeGameModel_0(
          this,
          Invocation.method(
            #executeAction,
            [
              gameId,
              action,
              direction,
            ],
          ),
        )),
      ) as _i4.Future<_i2.GameModel>);

  @override
  _i4.Future<_i2.GameModel> autoPlay(String? gameId) => (super.noSuchMethod(
        Invocation.method(
          #autoPlay,
          [gameId],
        ),
        returnValue: _i4.Future<_i2.GameModel>.value(_FakeGameModel_0(
          this,
          Invocation.method(
            #autoPlay,
            [gameId],
          ),
        )),
      ) as _i4.Future<_i2.GameModel>);

  @override
  _i4.Future<List<Map<String, dynamic>>> replayGame(String? gameId) =>
      (super.noSuchMethod(
        Invocation.method(
          #replayGame,
          [gameId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);
}
